/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fairMTSP.main

import ilog.cplex.IloCplex

class App {
    /*
    @param greeting variable with a getter function
     */
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    val controller = Controller()
    controller.parseArgs(args)
    controller.populateInstance()
    controller.run()
}
