/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fairMTSP.main


fun main(args: Array<String>) {
    val controller = Controller()
    controller.parseArgs(args)
    controller.populateInstance()
    controller.run()
}
