/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package FairMTSP

class App {
    /*
    @param greeting variable with a getter function
     */
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
}
